# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64224549dae35274916eebe2b59c40120a7f50e2c385bc9e9be5e2e439c59d41707de302bd59bc43e750bb8980e84f109bf4bd70e3ffef63dd6edccb942125b3

test:
  secret_key_base: cbe143d56f07cbfe4056dcff9f6e62ec9be5a45aa8fe6a8c616a0b486ebf2d7eb929ac8b4086b52eceaab40238d1c9903ad3e40451cbfc14ad2fa26e5d0c32c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
